name: deploy build to server

on:

    workflow_call:

jobs:
    
    deploy_build:
        runs-on: ubuntu-latest
        env:
            DOCKER_USER: ${{vars.DOCKER_USERNAME}}
            DOCKER_TAG: ${{github.sha}}
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: ssh remote server and install docker and docker compose
              uses: appleboy/ssh-action@v1
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USERNAME }}
                key: ${{ secrets.EC2_KEY }}
                script: |
                  echo "Successfully logged in"
                  sudo apt-get update && sudo apt install docker.io docker-compose-v2 -y
                  sudo usermod -aG docker $USER && newgrp docker
                  mkdir -p flasp_app_deployment
   
            - name: Copy files via SSH
              uses: appleboy/scp-action@v1
              with:
                 host: ${{ secrets.EC2_HOST }}
                 username: ${{ secrets.EC2_USERNAME }}
                 key: ${{ secrets.EC2_KEY }}
                 source: "docker-compose.yml"
                 target: ~/flasp_app_deployment  

            - name: deploying the app
              uses: appleboy/ssh-action@v1
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USERNAME }}
                key: ${{ secrets.EC2_KEY }}
                script: |
                  export DOCKER_USER=${{ vars.DOCKER_USERNAME }}
                  export DOCKER_TAG=${{ github.sha }}
                  echo ${{secrets.DOCKER_TOKEN}} | docker login --username ${{vars.DOCKER_USERNAME}} --password-stdin
                  cd ~/flasp_app_deployment && docker compose down && docker compose up -d --build --force-recreate --pull always

