name: devsecops pipeline
on: 
   workflow_dispatch: 
  #push:
    #branches: [main]

jobs:
    #CI
    code-quality_scan:
        uses: ./.github/workflows/code_quality_checker.yml
    secrets_scan:
        uses: ./.github/workflows/secrets_scan.yml  
        secrets: inherit
    dependency_scan:
         uses: ./.github/workflows/dependency_scanner.yml  
    docker_file_scan:
         uses: ./.github/workflows/docker_file_scanner.yml 
    build:
         needs: [code-quality_scan,secrets_scan,dependency_scan,docker_file_scan] 
         uses: ./.github/workflows/docker_build_push.yml
         secrets: inherit 

    trivy:
        needs: [build]
        uses: ./.github/workflows/docker_image_scanner.yml
        secrets: inherit 


     #CD
     
    deploy_app:
        needs: [trivy]
        uses: ./.github/workflows/deploy_to_server.yml
        secrets: inherit

