#name of the workflows
name : Hello

#workflows trigger on PR
on :
  workflow_dispatch: 
    
#defination of jobs
jobs:
   #defination of job
   greet :
      runs-on : ubuntu-latest    # github hosted runner

      #below steps will get perfomed in this jobe 
      steps:
        - name : say hello to all
          run : echo "Hello Dosto"

        - name: say hello to users
          run : echo "hello $USER"
          
      
   details:
        runs-on : ubuntu-latest
        steps:
          - name : need to verify the version of docker && python
            run : docker --version && python --version
      
